<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable, SoftDeletes;

    protected $fillable = [
        'name',
        'email',
        'password',
        'role',
        'department_id',
        'manager_id',
    ];

    protected $hidden = [
        'password',
        'remember_token',
    ];

    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
        'role' => 'string',
    ];

    // Relationships
    public function department()
    {
        return $this->belongsTo(Department::class);
    }

    public function manager()
    {
        return $this->belongsTo(User::class, 'manager_id');
    }

    public function interns()
    {
        return $this->hasMany(User::class, 'manager_id');
    }

    // Tasks assigned TO this user
    public function assignedTasks()
    {
        return $this->hasMany(Task::class, 'assigned_to');
    }

    // Tasks assigned BY this user
    public function createdTasks()
    {
        return $this->hasMany(Task::class, 'assigned_by');
    }

    // Reports generated by this user
    public function reports()
    {
        return $this->hasMany(Report::class, 'generated_by');
    }

    // Evaluations received (as intern)
    public function evaluations()
    {
        return $this->hasMany(Evaluation::class, 'intern_id');
    }

    // Evaluations given (as manager)
    public function givenEvaluations()
    {
        return $this->hasMany(Evaluation::class, 'manager_id');
    }

    // Attendance records
    public function attendances()
    {
        return $this->hasMany(Attendance::class, 'intern_id');
    }

    // Attendance records created by this user
    public function recordedAttendances()
    {
        return $this->hasMany(Attendance::class, 'recorded_by');
    }

    // Reclamations submitted
    public function reclamations()
    {
        return $this->hasMany(Reclamation::class, 'intern_id');
    }

    // Reclamations received (as manager)
    public function receivedReclamations()
    {
        return $this->hasMany(Reclamation::class, 'manager_id');
    }

    // Notifications sent
    public function sentNotifications()
    {
        return $this->hasMany(Notification::class, 'sender_id');
    }

    // Notifications received
    public function notificationRecipients()
    {
        return $this->hasMany(NotificationRecipient::class, 'recipient_id');
    }

    // Helper methods
    public function isAdmin()
    {
        return $this->role === 'admin';
    }

    public function isManager()
    {
        return $this->role === 'manager';
    }

    public function isIntern()
    {
        return $this->role === 'intern';
    }

    public function hasRole($role)
    {
        return $this->role === $role;
    }
}