import { format } from "date-fns";

export const exportReportToJSON = (report: any, filename?: string) => {
   const reportData = {
      title: `${
         report.type.charAt(0).toUpperCase() + report.type.slice(1)
      } Report`,
      period: `${report.period_start} to ${report.period_end}`,
      department: report.department?.name || "All Departments",
      generated_by: report.generated_by_user?.name || "Unknown",
      generated_at: format(new Date(report.created_at), "PPP"),
      data: report.data,
   };

   const dataStr = JSON.stringify(reportData, null, 2);
   const dataBlob = new Blob([dataStr], { type: "application/json" });
   const url = URL.createObjectURL(dataBlob);
   const link = document.createElement("a");
   link.href = url;
   link.download =
      filename ||
      `report-${report.type}-${report.id}-${format(
         new Date(),
         "yyyy-MM-dd"
      )}.json`;
   document.body.appendChild(link);
   link.click();
   document.body.removeChild(link);
   URL.revokeObjectURL(url);
};

export const exportReportToCSV = (report: any, filename?: string) => {
   let csvContent = "";

   // Header
   csvContent += `Report Type,${report.type}\n`;
   csvContent += `Period,${report.period_start} to ${report.period_end}\n`;
   csvContent += `Department,${report.department?.name || "All Departments"}\n`;
   csvContent += `Generated By,${
      report.generated_by_user?.name || "Unknown"
   }\n`;
   csvContent += `Generated At,${format(
      new Date(report.created_at),
      "PPP"
   )}\n\n`;

   // Data
   if (report.type === "attendance" && report.data) {
      csvContent += "Metric,Value\n";
      csvContent += `Total Records,${report.data.total || 0}\n`;
      csvContent += `Present,${report.data.present || 0}\n`;
      csvContent += `Absent,${report.data.absent || 0}\n`;
      csvContent += `Late,${report.data.late || 0}\n`;
      csvContent += `Excused,${report.data.excused || 0}\n`;
      csvContent += `Attendance Rate,${report.data.attendance_rate || 0}%\n`;
   } else if (report.type === "performance" && report.data) {
      csvContent += "Metric,Value\n";
      csvContent += `Total Evaluations,${report.data.total_evaluations || 0}\n`;
      csvContent += `Average Score,${report.data.average_score || 0}%\n`;
      csvContent += `Highest Score,${report.data.highest_score || 0}%\n`;
      csvContent += `Lowest Score,${report.data.lowest_score || 0}%\n`;
   }

   const dataBlob = new Blob([csvContent], { type: "text/csv" });
   const url = URL.createObjectURL(dataBlob);
   const link = document.createElement("a");
   link.href = url;
   link.download =
      filename ||
      `report-${report.type}-${report.id}-${format(
         new Date(),
         "yyyy-MM-dd"
      )}.csv`;
   document.body.appendChild(link);
   link.click();
   document.body.removeChild(link);
   URL.revokeObjectURL(url);
};
